---
 - name: Install yazi from cargo
   ansible.builtin.shell: cargo install --locked yazi-fm yazi-cli

 - name: hide preview
   ansible.builtin.shell:  ya pkg add yazi-rs/plugins:max-preview
   ignore_errors: true

 - name: yazi flavor
   ansible.builtin.shell:  ya pkg add yazi-rs/flavors:catppuccin-mocha  
   ignore_errors: true

 - name: yazi full bolder
   ansible.builtin.shell: ya pkg add yazi-rs/plugins:full-border 
   ignore_errors: true

 - name: yazi upgrade
   ansible.builtin.shell: ya pkg upgrade
   ignore_errors: true
