---
- name: Download the latest Neovim release
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim-linux-arm64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
    mode: '0644'

- name: Remove existing Neovim installation
  ansible.builtin.file:
    path: /opt/nvim
    state: absent

- name: Extract Neovim to /opt
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes

- name: Clean up the downloaded tarball
  ansible.builtin.file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent

# - name: Update packer
#   ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
# - name: Update mason
#   ansible.builtin.command: nvim --headless -c 'MasonUpdate' -c 'q'

