---
- name: Ensure .bashrc sources .bash_customization
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source ~/.bash_customization.sh"
    create: true
    state: present
  register: bashrc_updated

- name: Source the shell configuration file
  ansible.builtin.shell: |
    source ~/.bashrc
    echo "Changes to ~/.bashrc sourced"
