---
 - name: Download kitty installer script
   ansible.builtin.get_url:
     url: https://sw.kovidgoyal.net/kitty/installer.sh
     dest: /tmp/kitty_installer.sh
     mode: '0755'
 - name: Execute kitty installer script
   ansible.builtin.shell: /tmp/kitty_installer.sh launch=n
 - name: Check Kitty version
   command: kitty -v
   register: kitty_version
   ignore_errors: true
   changed_when: false
 - name: Print Kitty version
   debug:
     msg: "Kitty is installed. Version: {{ kitty_version.stdout }}"
 - name: Check if kitty.desktop exists
   stat:
     path: "~/.local/share/applications/kitty.desktop"
   register: kitty_desktop
 - name: Create symbolic links for kitty and kitten
   shell: ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/
   when: not kitty_desktop.stat.exists
 - name: Copy kitty.desktop to applications directory
   shell: cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
   when: not kitty_desktop.stat.exists
 - name: Copy kitty-open.desktop to applications directory
   shell: cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
   when: not kitty_desktop.stat.exists
 - name: Update paths in kitty desktop files
   shell: |
     sed -i "s|Icon=kitty|Icon=become: true/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" become: true/.local/share/applications/kitty*.desktop
     sed -i "s|Exec=kitty|Exec=become: true/.local/kitty.app/bin/kitty|g" become: true/.local/share/applications/kitty*.desktop
   when: not kitty_desktop.stat.exists
 - name: Set kitty as the default terminal in xdg-terminal-exec
   shell: echo 'kitty.desktop' > ~/.config/xdg-terminals.list
   when: not kitty_desktop.stat.exists
