---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Cleanup
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
- name: Upgrade packages
  apt:
    upgrade: dist
- name: Install 
  ansible.builtin.apt:
    name:
    - cowsay
    - python3
    - git
    - tar
    - jq
    - bat  
    - xclip
    - sqlite3
    - libfuse2
    - wmctrl
    - libsqlite3-dev
    - lolcat
    - lynis
    - auditd
    - debsums
    - obs-studio 
    - ffmpeg 
    - pipewire
    - stow
    - sox
    - fonts-noto-color-emoji
    - clamav
    - tmux
    - npm
    - ntfs-3g
    - ufw
    - texlive
    # - xmllint
- name: Ensure tmux plugin manager directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    state: directory
    mode: '0755'

- name: Clone TPM repository
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    force: yes
    update: yes

- name: Trigger tmux plugin installation
  ansible.builtin.shell: |
    tmux new-session -d -s temp_session
    tmux run-shell ~/.tmux/plugins/tpm/bin/install_plugins
    tmux kill-session -t temp_session
  args:
    executable: /bin/bash
  when: "'tmux' in ansible_env.PATH"
- name: Ensure Git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Configure Git autocorrect
  ansible.builtin.command:
    cmd: git config --global help.autocorrect 1

- name: Enable Git rerere
  ansible.builtin.command:
    cmd: git config --global rerere.enabled true
