---
- name: Fetch fzf
  ansible.builtin.command: git clone --depth 1 https://github.com/junegunn/fzf.git 
  ignore_errors: true
- name: Update fzf
  ansible.builtin.command:  git pull
  args:
    chdir: fzf
- name: Install fzf
  ansible.builtin.command: ./fzf/install --all
